/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChatRouteRouteImport } from './routes/chat/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as ChatNewRouteImport } from './routes/chat/new'
import { Route as ChatRoomIdRouteImport } from './routes/chat/$roomId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRouteRoute = ChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRouteRoute,
} as any)
const ChatNewRoute = ChatNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ChatRouteRoute,
} as any)
const ChatRoomIdRoute = ChatRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => ChatRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/chat/$roomId': typeof ChatRoomIdRoute
  '/chat/new': typeof ChatNewRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/chat/$roomId': typeof ChatRoomIdRoute
  '/chat/new': typeof ChatNewRoute
  '/chat': typeof ChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/chat/$roomId': typeof ChatRoomIdRoute
  '/chat/new': typeof ChatNewRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chat' | '/login' | '/chat/$roomId' | '/chat/new' | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/chat/$roomId' | '/chat/new' | '/chat'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/login'
    | '/chat/$roomId'
    | '/chat/new'
    | '/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRouteRoute: typeof ChatRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRouteRoute
    }
    '/chat/new': {
      id: '/chat/new'
      path: '/new'
      fullPath: '/chat/new'
      preLoaderRoute: typeof ChatNewRouteImport
      parentRoute: typeof ChatRouteRoute
    }
    '/chat/$roomId': {
      id: '/chat/$roomId'
      path: '/$roomId'
      fullPath: '/chat/$roomId'
      preLoaderRoute: typeof ChatRoomIdRouteImport
      parentRoute: typeof ChatRouteRoute
    }
  }
}

interface ChatRouteRouteChildren {
  ChatRoomIdRoute: typeof ChatRoomIdRoute
  ChatNewRoute: typeof ChatNewRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteRouteChildren: ChatRouteRouteChildren = {
  ChatRoomIdRoute: ChatRoomIdRoute,
  ChatNewRoute: ChatNewRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteRouteWithChildren = ChatRouteRoute._addFileChildren(
  ChatRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRouteRoute: ChatRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
